image: node:7

before_script:
    - npm install

cache:
  paths:
    - node_modules/

stages:
    - test

lint:
  stage: test
  script:
    - npm run lint

build:
  stage: test
  script:
    - npm run build
